obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[0.363, 0.3085], [0.363, -0.3085], [-0.363, -0.3085], [-0.363, 0.3085]]
footprint_inflation: 0.01
robot_radius: 0.3085
inflation_radius: 0.15
max_obstacle_height: 0.6
min_obstacle_height: 0.0
observation_sources: scan
scan: {data_type: LaserScan, topic: /rslidar/scan, marking: true, clearing: true, expected_update_rate: 0}
