arm:
  arm_joint_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6

    gains:
      joint1:   {p: 10000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      joint2:   {p: 10000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      joint3:   {p: 10000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      joint4:   {p: 10000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      joint5:   {p: 10000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      joint6:   {p: 10000.0, i: 0.0, d: 0.1, i_clamp: 0.0}

  gripper_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - robotiq_85_left_knuckle_joint
    constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      finger_joint: {trajectory: 0.01, goal: 0.01}
    stop_trajectory_duration: 0.5
    state_publish_rate:  25
    action_monitor_rate: 10

#arm/gazebo_ros_control/pid_gains:
      #joint1:   {p: 10000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      #joint2:   {p: 10000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      #joint3:   {p: 10000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      #joint4:   {p: 10000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      #joint5:   {p: 10000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      #joint6:   {p: 10000.0, i: 0.0, d: 0.1, i_clamp: 0.0}


